### ISSUE TITLE
Problemas con la Convivencia entre TV conectada y Script habilitado

### ISSUE THREAD

**Issue by fernando-inf** [generiz/AnydeskVirtualDisplayFix#1]
Hola, el Script funciona muy bien siempre que no se conecte ningún monitor o TV. Pero cuando se conecta una TV o Monitor hay que desinstalar antes el Script, luego apagar la PC (manteniendo apretado el botón de apagado), para luego poder utilizar la TV/Monitor.

Sería bueno que el programa detecte al iniciar el sistema operativo que ya hay conectado un monitor, a los efectos de evitar ejecutarse. De esta forma con solo reiniciar la computadora se solucionaría el problema. Gracias.

P.D: Aclaro que la PC que estoy usando es un INTEL NUC NUC8i3BEH (Windows 10)

**Comment by generiz** [comment]
Hola,

Quiero agradecerte por señalar el problema con los monitores externos al iniciar el sistema operativo. He trabajado en una solución basada en tus comentarios y aquí te describo los cambios realizados:

Detección Automática de Monitores Externos: Ahora el script detecta automáticamente si hay un monitor o TV externos conectados durante el inicio del sistema.

Gestión del Virtual Display: Si se detecta un monitor externo, el script deshabilitará automáticamente el Virtual Display para evitar conflictos.

Optimización del Flujo: He modificado la secuencia en tarea.ps1 para que sea más eficiente y solo realice las operaciones necesarias según el contexto.

Te recomendaría que descargues la última versión del script y pruebes estos cambios. Espero que estos ajustes resuelvan el problema que experimentaste.

Para actualizar:

Descarga la última versión del script.
Sigue las instrucciones habituales de instalación.
Reinicia tu sistema para que los cambios tengan efecto.
Te agradezco nuevamente por tu paciencia y feedback. No dudes en informarme si encuentras otros problemas o tienes más sugerencias.

Saludos,
